---
title: "QMM Assignment 6"
author: "Hanish Bhogadi"
date: '2022-11-21'
output:
  pdf_document: default
  html_document: default
---

```{r}
library(lpSolve)
library(lpSolveAPI)
x<- read.lp("/Users/Hanish Bhogadi/Downloads/ap.lp")
x
```


```{r}
solve(x)
```
```{r}
get.objective(x)
```

The total cost of the minimal wage expense is $25,675. 

```{r}
get.variables(x)
```

```{r}
table1 <- matrix(c(0,4,5,0,8,1,0,0,0,5,0,8,1,13,2,0,0,0,8,1,13,2,4,0,0,8,1,13,2,4,5,0,0,1,13,2,3,4,0,0,0,13,2,4,5,0,8,0,0), ncol=7,byrow=TRUE)
colnames(table1)<- c('Sun/Mon', 'Mon/Tue','Tue/Wed', 'Wed/Thur', 'Thur/Fri', 'Fri/Sat', 'Sat/Sun')
row.names(table1) <- c('Sunday', 'Monday', 'Tuesday','Wednesda','Thursday','Friday','Saturday')
table1
```
Using the variables from the lp model, To find the optimal solution, I inserted the variables into the schedule as it minimizes the total wage expense. 

```{r}
rowSums(table1)
```
Using the shift schedule, this table shows the  number of employees available each day that minimizes the total wage expense. 